---
- Administração:
    - CasaOS:
        icon: casaos.svg
        href: http://aphome201.local
        description: Gerenciamento do Raspberry Pi
        server: local
        container: ""

    - Portainer:
        icon: portainer.svg
        href: http://portainer.aphome201:9000
        description: Gerenciamento Docker
        server: local
        container: dc-portainer

- Infraestrutura:
    - Dozzle:
        icon: dozzle.svg
        href: http://log.aphome201:8888
        description: Logs dos containers Docker
        server: local
        container: dc-dozzle

    - Beszel:
        icon: beszel.svg
        href: http://aphome201:8090
        description: Monitoramento do Raspberry Pi
        server: local
        container: dc-beszel

    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.svg
        href: http://aphome201.local:81
        description: Reverse Proxy
        server: local
        container: dc-nginx-proxy-manager

- Rede:
    - AdGuard Home:
        icon: adguard-home.svg
        href: http://aphome201.local:3001
        description: DNS e bloqueio de anúncios
        server: local
        container: dc-adguard-home

    - MySpeed:
        icon: myspeed.svg
        href: http://myspeed.aphome201:5216
        description: Monitoramento da velocidade da Internet
        server: local
        container: dc-myspeed

- Armazenamento:
    - File Browser:
        icon: filebrowser.svg
        href: http://file.aphome201:10180/
        description: Gerenciamento de arquivos
        server: local
        container: dc-filebrowser

    - SFTPGo:
        icon: sftpgo.svg
        href: http://sftp.aphome201:8080
        description: Transferência e gerenciamento de arquivos
        server: local
        container: dc-sftpgo

- Financeiro:
    - Finance Dashboard:
        icon: homebank.svg
        href: http://dashboard.aphome201:8085/dashboard.html
        description: Gerenciamento financeiro pessoal
        server: local
        container: dc-finance-dash
    
    - Finance Insert:
        icon: homebank.svg
        href: http://dashboard.aphome201:8085/insert.html
        description: Inserção de dados financeiros
        server: local
        container: dc-finance-api