# name|source|destination|files
homepage|/home/dalves/automation/configs-apps/homepage|/DATA/AppData/big-bear-homepage/config|*.yaml
raspberry-scripts|/home/dalves/automation/raspberry-scripts/scripts-bin|/usr/local/bin|docker-containers.conf,docker_morning_start.sh,docker_night_stop.sh,cpu_alert.sh,temp_alert.sh
